# Generated by Django 2.0 on 2019-08-15 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('body', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('middle_name', models.CharField(default='', max_length=200)),
                ('sex', models.CharField(default='', max_length=10)),
                ('Registration_Number', models.CharField(default='', max_length=200)),
                ('current_session', models.CharField(default='', max_length=200)),
                ('current_term', models.CharField(default='', max_length=200)),
                ('current_class', models.CharField(default='', max_length=5)),
                ('average', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=3)),
                ('position', models.CharField(default='', max_length=500)),
                ('total_subject', models.CharField(default='', max_length=30)),
                ('percentage', models.CharField(default='', max_length=3)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_Number', models.CharField(max_length=50)),
                ('current_session', models.CharField(max_length=50)),
                ('current_class', models.CharField(default='', max_length=10)),
                ('pin', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myclass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(default='media', upload_to='')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='published', max_length=15)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('kg1', 'kg1'), ('kg2', 'kg2'), ('kg3', 'kg3'), ('pry1', 'pry1'), ('pry2', 'pry2'), ('pry3', 'pry3'), ('pry4', 'pry4'), ('pry5', 'pry5'), ('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], max_length=10)),
                ('purpose', models.CharField(choices=[('School Fees', 'School Fees'), ('P.T.A', 'P.T.A')], max_length=20)),
                ('fee', models.CharField(choices=[('50', '50'), ('60', '60')], max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('Registration_Number', models.CharField(max_length=12, unique=True)),
                ('Phone', models.CharField(default='+234', max_length=30)),
                ('Address', models.CharField(max_length=600)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('current_class', models.CharField(choices=[('kg1', 'kg1'), ('kg2', 'kg2'), ('kg3', 'kg3'), ('pry1', 'pry1'), ('pry2', 'pry2'), ('pry3', 'pry3'), ('pry4', 'pry4'), ('pry5', 'pry5'), ('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], default='', max_length=5)),
                ('average', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveIntegerField(default='0')),
                ('pin', models.CharField(default='', max_length=100)),
                ('total_course', models.PositiveIntegerField(default=0)),
                ('year', models.IntegerField(help_text='enter year of birth')),
                ('month', models.IntegerField(help_text='enter month of birth')),
                ('day', models.IntegerField(help_text='enter day of birth')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_Number', models.CharField(max_length=50)),
                ('current_class', models.CharField(default='', max_length=5)),
                ('first_test', models.PositiveIntegerField(default=0)),
                ('second_test', models.PositiveIntegerField(default=0)),
                ('exam', models.PositiveIntegerField(default=0)),
                ('average', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrator.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('no', models.CharField(default='0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st term'), ('2nd term', '2nd term'), ('3rd term', '3rd term')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Subject'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session'),
        ),
        migrations.AddField(
            model_name='payments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Student'),
        ),
        migrations.AddField(
            model_name='payments',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session'),
        ),
        migrations.AddField(
            model_name='currentterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Term'),
        ),
        migrations.AddField(
            model_name='currentsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Session'),
        ),
    ]
