# Generated by Django 2.0 on 2019-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentterm',
            name='term',
            field=models.CharField(choices=[('1st term', '1st term'), ('2nd term', '2nd term'), ('3rd term', '3rd term')], max_length=20),
        ),
    ]
