# Generated by Django 2.0 on 2019-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190815_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='no',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_student',
            field=models.CharField(choices=[('kg1', 'kg1'), ('kg2', 'kg2'), ('kg3', 'kg3'), ('pry1', 'pry1'), ('pry2', 'pry2'), ('pry3', 'pry3'), ('pry4', 'pry4'), ('pry5', 'pry5'), ('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
