# Generated by Django 2.0 on 2019-09-01 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190821_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subject',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='administrator.Student'),
        ),
    ]
