# Generated by Django 2.0 on 2019-09-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190901_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subject',
            name='term',
            field=models.CharField(choices=[('1st term', '1st term'), ('2nd term', '2nd term'), ('3rd term', '3rd term')], default='1st term', max_length=10),
        ),
    ]
