# Generated by Django 2.0 on 2019-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentterm',
            name='term',
            field=models.CharField(choices=[('1ST TERM', '1ST TERM'), ('2ND TERM', '2ND TERM'), ('3RD TERM', '3RD TERM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payments',
            name='student_class',
            field=models.CharField(choices=[('KG1', 'KG1'), ('KG2', 'KG2'), ('KG3', 'KG3'), ('PRY1', 'PRY1'), ('PRY2', 'PRY2'), ('PRY3', 'PRY3'), ('PRY4', 'PRY4'), ('PRY5', 'PRY5'), ('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.CharField(choices=[('KG1', 'KG1'), ('KG2', 'KG2'), ('KG3', 'KG3'), ('PRY1', 'PRY1'), ('PRY2', 'PRY2'), ('PRY3', 'PRY3'), ('PRY4', 'PRY4'), ('PRY5', 'PRY5'), ('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_term',
            field=models.CharField(choices=[('1ST TERM', '1ST TERM'), ('2ND TERM', '2ND TERM'), ('3RD TERM', '3RD TERM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='term',
            field=models.CharField(choices=[('1ST TERM', '1ST TERM'), ('2ND TERM', '2ND TERM'), ('3RD TERM', '3RD TERM')], default='1ST TERM', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_student',
            field=models.CharField(choices=[('KG1', 'KG1'), ('KG2', 'KG2'), ('KG3', 'KG3'), ('PRY1', 'PRY1'), ('PRY2', 'PRY2'), ('PRY3', 'PRY3'), ('PRY4', 'PRY4'), ('PRY5', 'PRY5'), ('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(choices=[('1ST TERM', '1ST TERM'), ('2ND TERM', '2ND TERM'), ('3RD TERM', '3RD TERM')], max_length=20),
        ),
    ]
