# Generated by Django 2.0 on 2019-10-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_assignmentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('assignment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_name', to='administrator.AssignmentName')),
            ],
        ),
    ]
