# Generated by Django 2.2.1 on 2019-10-30 01:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_assignmentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('Registration_Number', models.CharField(max_length=30)),
                ('current_class', models.CharField(choices=[('kg1', 'kg1'), ('kg2', 'kg2'), ('kg3', 'kg3'), ('pry1', 'pry1'), ('pry2', 'pry2'), ('pry3', 'pry3'), ('pry4', 'pry4'), ('pry5', 'pry5'), ('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], default='', max_length=5)),
                ('purpose', models.CharField(choices=[('School Fees', 'School Fees'), ('P.T.A', 'P.T.A'), ('Lesson Fee', 'Lesson Fee')], max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.CharField(choices=[('50', '50')], default=100, max_length=200)),
                ('current_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Session')),
                ('current_term', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.Term')),
            ],
        ),
    ]
