# Generated by Django 2.2.1 on 2019-10-30 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_studentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='Registration_Number',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_payment', to='administrator.Student'),
            preserve_default=False,
        ),
    ]
