# Generated by Django 2.2.1 on 2019-10-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20191030_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalresult',
            old_name='middle_name',
            new_name='last_name',
        ),
    ]
