# Generated by Django 3.0 on 2023-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20191030_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_term',
            field=models.CharField(choices=[('1ST SEMESTER', '1ST SEMESTER'), ('2ND SEMESTER', '2ND SEMESTER')], max_length=40),
        ),
    ]
