# Generated by Django 3.0 on 2023-09-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20230920_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalresult',
            old_name='current_term',
            new_name='current_level',
        ),
        migrations.RenameField(
            model_name='generalresult',
            old_name='current_class',
            new_name='current_semester',
        ),
        migrations.RenameField(
            model_name='generatepin',
            old_name='current_class',
            new_name='current_semester',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_class',
            new_name='current_level',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_term',
            new_name='current_semester',
        ),
        migrations.RenameField(
            model_name='student_subject',
            old_name='current_class',
            new_name='current_semester',
        ),
        migrations.RenameField(
            model_name='studentpayment',
            old_name='current_term',
            new_name='current_level',
        ),
        migrations.RenameField(
            model_name='studentpayment',
            old_name='current_class',
            new_name='current_semester',
        ),
    ]
