# Generated by Django 2.2.1 on 2019-10-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
